server:
  port: 8100
  error:
    include-message: always

spring:
  application:
    name: admin
  data:
    mongodb:
      host: localhost
      port: 27017
      database: reservago-admin
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 5s

springdoc:
  swagger-ui:
    path: /swagger-doc/admin

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
