server:
  servlet:
    context-path: /admin
  port: 8100
  server:
    error:
      include-message: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/admin
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
