server:
  port: 8102
  error:
    include-message: always

spring:
  application:
    name: checkout
  data:
    mongodb:
      host: localhost
      port: 27017
      database: reservago-checkout

springdoc:
  swagger-ui:
    path: /swagger-doc/checkout

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

admin:
  server:
    name: localhost:8100
payment:
  server:
    name: localhost:8101
