server:
  port: 8080

spring:
  application:
    cloud:
      loadbalancer:
        ribbon:
          enabled: false

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
