server.port: 9003

spring:
  application.name: logger-fn
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 5s
  cloud.stream.bindings:
    log-in-0.destination: logging

