server.port: 9004

spring:
  application.name: process-place-creation-fn
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 5s
  cloud.stream.bindings:
    processPlaceCreation-out-0.destination: logging

