server.port: 9005

spring:
  application.name: verify-place-available-fn
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 5s
  cloud.stream.bindings:
    verifyPlaceAvailable-out-0.destination: logging

